# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'draft1.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import backend_file as backend
from PyQt5 import QtCore, QtGui, QtWidgets
import threading
import queue

server = backend.myServer()

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(400, 300)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(29, 29, 341, 211))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")

        #Row 1
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ipLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ipLabel.setFont(font)
        self.ipLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ipLabel.setObjectName("ipLabel")
        self.horizontalLayout.addWidget(self.ipLabel)

        self.ipValue = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ipValue.setFont(font)
        self.ipValue.setObjectName("ipValue")
        self.horizontalLayout.addWidget(self.ipValue)
        self.verticalLayout.addLayout(self.horizontalLayout)

        #Row 2
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.portLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.portLabel.setFont(font)
        self.portLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.portLabel.setObjectName("portLabel")
        self.horizontalLayout_3.addWidget(self.portLabel)
        self.portValue = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.portValue.setFont(font)
        self.portValue.setObjectName("portValue")

        self.horizontalLayout_3.addWidget(self.portValue)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        #Row 3
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")

        self.statusLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.statusLabel.setFont(font)
        self.statusLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.statusLabel.setObjectName("statusLabel")
        self.horizontalLayout_4.addWidget(self.statusLabel)
        self.statusValue = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.statusValue.setFont(font)
        self.statusValue.setObjectName("statusValue")
        self.horizontalLayout_4.addWidget(self.statusValue)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ipLabel.setText(_translate("MainWindow", "IP Address: "))
        self.ipValue.setText(_translate("MainWindow", server.server))
        self.portLabel.setText(_translate("MainWindow", "Port: "))
        self.portValue.setText(_translate("MainWindow", str(server.port)))
        self.statusLabel.setText(_translate("MainWindow", "Status:"))
        self.statusValue.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ff0000;\">Not Connected</span></p></body></html>"))

    def statusChecker(self, queue):
        _translate = QtCore.QCoreApplication.translate
        #TODO
        while True:
            result = q.get()
            if result == True:
                self.statusValue.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#008000;\">Connected</span></p></body></html>"))
            if isinstance(result, str):
                self.statusValue.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#008000;\">"+ result +"</span></p></body></html>"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()

    q = queue.Queue()

    thread = threading.Thread(target=server.run, daemon=True, args=(q,))
    thread.start()

    thread2 = threading.Thread(target=ui.statusChecker, daemon=True, args=(q,))
    thread2.start()

    sys.exit(app.exec_())

